[project]
name = "cspresso"
version = "0.1.5"
description = "Crawl a website with a headless browser and generate a draft Content-Security-Policy (CSP)."
authors = [{ name = "Miguel Jacq", email = "mig@mig5.net" }]
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.10,<4.0"
dependencies = ["playwright>=1.50.0,<2.0.0"]

[project.urls]
Homepage = "https://cspresso.cafe"
Repository = "https://git.mig5.net/mig5/cspresso"

[project.scripts]
cspresso = "cspresso.crawl:main"

[tool.poetry]
requires-poetry = ">=2.2,<3.0"
packages = [{ include = "cspresso", from = "src" }]

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-cov = "^5"
pyproject-appimage = "^4.2"

[build-system]
requires = ["poetry-core>=2.2,<3.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyproject-appimage]
script = "cspresso"
output = "CSPresso.AppImage"
